web:
    container_name: web
    build: ./images/php5.4-apache
    ports:
        - 80:80
    links:
        - db
        - search        
    volumes:
        - /Users/cedric/sugar-docker-example/data/web:/var/www/html
db:
    container_name: db
    image: percona:5.6
    environment:
        - MYSQL_ROOT_PASSWORD=root
    ports:
        - 3306:3306
    volumes:
        - /Users/cedric/sugar-docker-example/data/mysql:/var/lib/mysql
search:
    container_name: search
    image: elasticsearch:1.4
    ports:
        - 9200:9200
        - 9300:9300
    volumes:
        - /Users/cedric/sugar-docker-example/data/elasticsearch:/usr/share/elasticsearch/data